# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('nameChannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('previous_ranking', models.PositiveIntegerField(default=2147483648.0)),
                ('previous_plays', models.PositiveIntegerField(default=2147483648.0)),
                ('namePerformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.Performer')),
            ],
        ),
        migrations.AddField(
            model_name='play',
            name='nameSong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.Song'),
        ),
    ]
