# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='previous_plays',
        ),
        migrations.RemoveField(
            model_name='song',
            name='previous_ranking',
        ),
        migrations.AlterField(
            model_name='song',
            name='namePerformer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performer', to='webapi.Performer'),
        ),
    ]
